### ISSUE TITLE
Pod not pushed to cocoapods

### ISSUE THREAD

**Issue by joncravotta** [thomassnielsen/SwiftyJSONAPI#12]
Hey, can you please push the latest tag to cocoapods?  0.0.19 has not yet been pushed.  The latest version is 0.0.18: https://cocoapods.org/pods/SwiftyJSONAPI

Thank you!

**Comment by thomassnielsen** [comment]
As noted in https://github.com/thomassnielsen/SwiftyJSONAPI/pull/11 I couldn’t because I didn’t have High Sierra on my Mac. Fortunately I upgraded this week, so I’ll get it done soon. Thanks for the reminder 🙏

**Comment by thomassnielsen** [comment]
0.0.19 has now been pushed to cocoapods 🚀
