### ISSUE TITLE
CircleCI is not picking up tests

### ISSUE THREAD

**Issue by thomassnielsen** [thomassnielsen/SwiftyJSONAPI#2]

**Comment by thomassnielsen** [comment]
CircleCI doesn't run our tests currently because they don't have enough iOS capacity. In any case, it should start working when they do after a535a210245b7e421c48f1cf76bf9271d83565fa.

**Comment by billyto** [comment]
It's been like 5 months and still seems like no iOS capacity, Should we try another provider like TravisCI?

Cheers,

**Comment by thomassnielsen** [comment]
Yes, it seems like the rollout of CircleCI iOS testing has taken way longer than I expected. I'm not currently using this project myself, and I'm heads down in a non-iOS project, but I'd gladly accept a pull request switching to another CI.

**Comment by billyto** [comment]
PR #1 now includes moving to travis-ci (via .travis.yml) but you will need to configure at [travis-ci.org](https:travis-ci.org) for **thomassnielsen/SwiftyJSONAPI**; I'd be happy to set it up, but I would need admin access to this repo.

**Comment by thomassnielsen** [comment]
Travis configured, see #1
