### ISSUE TITLE
tag 0.0.10 pointing to wrong commit

### ISSUE THREAD

**Issue by billyto** [thomassnielsen/SwiftyJSONAPI#5]
tag 0.0.10 is poiting to:
`Latest commit 6ff5d56  on Oct 17, 2015 @thomassnielsen thomassnielsen Version bump`

It should point to whatever is in master now, isn't it? or maybe have a new 0.0.11 or 0.1.0 version?
`Latest commit aa3b13f  on Mar 9 @thomassnielsen thomassnielsen Merge pull request #1 from RentTheRunway/master`

Thanks,

**Comment by thomassnielsen** [comment]
Thanks for reporting. I'll make a new 0.0.11 release pointing to the latest commit.

**Comment by thomassnielsen** [comment]
Done, and pushed to Cocoapods.
