### ISSUE TITLE
Update the tag

### ISSUE THREAD

**Issue by joncravotta** [thomassnielsen/SwiftyJSONAPI#7]
Hey Thomas,

Can we get a new tag cut for these 2.3 problems?

**Comment by thomassnielsen** [comment]
Sure thing. 0.0.12 tagged and pushed.

**Comment by billyto** [comment]
Seems like the tag was applied to the wrong commit, therefore see

https://github.com/thomassnielsen/SwiftyJSONAPI/compare/0.0.12...master

Shouldn't they be the same?

**Comment by thomassnielsen** [comment]
Sorry about that. Added a new tag 0.0.13 on a new version bump commit to avoid changing the history. https://github.com/thomassnielsen/SwiftyJSONAPI/compare/0.0.13...master looks correct now.

**Comment by billyto** [comment]
One last big favor! Could you push 0.0.13 to cocoapods repo? still showing 0.0.12.

Thanks!

**Comment by thomassnielsen** [comment]
Shows how long it's been, I just forgot. Pushing now.

**Comment by thomassnielsen** [comment]
Getting som errors about Swift version (3.0 is default now in Cocoapods it seems). May take me a bit of time to fix (and possibly another version bump).

**Comment by thomassnielsen** [comment]
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  SwiftyJSONAPI (0.0.14) successfully published
 📅  January 17th, 16:56
 🌎  https://cocoapods.org/pods/SwiftyJSONAPI
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

Hi friends! Now pushed to repo.
